### ISSUE TITLE
Undeprecate streams

### ISSUE THREAD

**Issue by tanlines** [powbot/api#11]
I understand you're trying to make us either fully use streams or fully use the query api, but I don't see the point. Often I'll use the query api to filter since it's easier than using stream.filter(), then convert it into a stream to perform conversions/mapping.

Unless you completely rewrite the functionality of streams and put it back into the api (which I don't recommend), don't deprecate streams.

https://github.com/powbot/api/blob/master/src/main/java/org/powerbot/script/AbstractQuery.java#L50

**Comment by constt** [comment]
Fair, done
