### ISSUE TITLE
Some widgets not aligned

### ISSUE THREAD

**Issue by tanlines** [powbot/api#13]
See image

https://i.imgur.com/a00xB9s.png

**Comment by RZME** [comment]
another case https://i.gyazo.com/e08755915f56097e5299b59271444e52.png

**Comment by constt** [comment]
Is this as a result of yesterdays update?

**Comment by RZME** [comment]
@constt no, experienced this prior to the update

**Comment by rvbiljouw** [comment]
have not yet been able to reproduce this with the latest release - would be helpful if you can find a f2p interface that exhibits this behavior. will leave open for now.

**Comment by RZME** [comment]
another one https://i.gyazo.com/dcc2980b7aeac912e8987a8e3e17eb0e.png. 
Will look for a f2p one
