### ISSUE TITLE
ctx.controller.script().log.info NPE

### ISSUE THREAD

**Issue by tanlines** [powbot/api#14]
Can't replicate but user is sending logs which point to this line causing NPE. No method calling in the log.info() part so either controller, script or log is null.

ctx.controller.script().log.info("........")

If there's a proper logging API built into client already let me know, this is just what was suggested previously.

**Comment by constt** [comment]
I've made a change which may fix this, please let me know.

**Comment by constt** [comment]
@tanlines Is this still an issue?

**Comment by MatoV** [comment]
Works fine for me
