### ISSUE TITLE
Improve interaction with ground items

### ISSUE THREAD

**Issue by MatoV** [powbot/api#21]
Right now if you don't specify the name of an item that you want to "Take", it will not right click and it will keep looting everything that's on top of the said item.
`groundItem.interact("Take");` will not right click, while
`groundItem.interact("Take", "itemName");` will.

**Comment by iDznPB** [comment]
This is the same with any .interact() method, you have to provide a polled object, whether that be an npc, item, groundItem, GameObject, either way, it would be good to have it take the name from the provided object.

**Comment by MatoV** [comment]
> ,it would be good to have it take the name from the provided object.
That's why I raised this. I think that most would assume that'd be the expected behaviour.

**Comment by constt** [comment]
Fixed in https://github.com/powbot/api/commit/c168535f5743999d67971a21020014caeb1150f2, will release tomorrow.
