### ISSUE TITLE
Prioritize bank booths and chests in getBank()

### ISSUE THREAD

**Issue by MatoV** [powbot/api#26]
https://github.com/powbot/api/blob/f9ff464ed1759ebb7814dee1a55e08f687a92aad/src/main/java/org/powerbot/script/rt4/Bank.java#L39

Prioritizing booths over bank npcs would fix the "_I can't reach that!_" problem. I's also one click less and in my opinion more natural.

![image](https://user-images.githubusercontent.com/15001453/99960589-49feb500-2d8d-11eb-8ce4-259f6d6b98b4.png)

**Comment by constt** [comment]
https://github.com/powbot/api/commit/df6d317613737bed61756b95a0d0760335d0b626 should do it
