### ISSUE TITLE
Projectile tile broken

### ISSUE THREAD

**Issue by iDznPB** [powbot/api#38]
ctx.projectiles.select().poll().tile() doesn't change as the projectile moves
however new Tile(ctx.projectiles.select().poll().getX(), ctx.projectiles.select().poll().getY());
does work.

Not a priority as there's a work around, just something to note.

**Comment by constt** [comment]
https://github.com/powbot/api/commit/29e0d26d4f0ebb471ba2c29037e7793eff9c4643 should fix it
