### ISSUE TITLE
Hint arrow hook broken

### ISSUE THREAD

**Issue by tanlines** [powbot/api#40]
Doing falconry, a hint arrow shows on the npc when you've caught it.

ctx.client().getHintArrowNpcUid() always returns 0

My method to get the npc the hint arrow is pointing to doesn't work anymore.

`public Tile hintArrow() {
        int[] n = ctx.client().getNpcIndices();
        for (int i = 0; i < n.length; i++) {
            if (n[i] == ctx.client().getHintArrowNpcUid()) {
                if (ctx.npcs.get().size() <= i) break;
                Npc falcon = ctx.npcs.get().get(i);
                if (!falcon.name().equals("Gyr Falcon")) continue;
                return ctx.npcs.get().get(i).tile();
            }
        }
        return Tile.NIL;
    }
`

**Comment by constt** [comment]
This has been resolved
