### ISSUE TITLE
Vial at NMZ is broken

### ISSUE THREAD

**Issue by iDznPB** [powbot/api#45]
![image](https://user-images.githubusercontent.com/34009165/105644336-0576bf00-5e8d-11eb-879b-48e8ac4f3f05.png)
ID: 26276
Location: 2605, 3116, 0

**Comment by constt** [comment]
https://github.com/powbot/api/commit/d00971a0c72083d58ba3bfa2bc14a72e24de3821 Will fix this, need to work out why some models are missing
