### ISSUE TITLE
Paint isn't consistent

### ISSUE THREAD

**Issue by iDznPB** [powbot/api#5]
Often have to restart the client to show the paint window.
Either painting through the PaintListener or painting through the clients debug menu.

**Comment by RZME** [comment]
Got the same issue

**Comment by constt** [comment]
Is there any output from the console, are you able to provide a short video please?

**Comment by iDznPB** [comment]
While watching the playback of the recording, I realised I was able to recreate this by resizing the client.
No output in the log at all but tested 6 times;
-Reloaded client
-Turned on mouse position
-Made client bigger
-Paint is completely gone
-Couldn't get it back without restarting client.

**Comment by constt** [comment]
fixed this internally
