### ISSUE TITLE
Web Walking API requests

### ISSUE THREAD

**Issue by PTYB** [powbot/api#59]
Hi,

 When using web walking there are some drawbacks which I believe can be addressed with a few simple API enhancements. **Note:** I have not extensively used web walking and am going to do some testing so this is first impressions from the API.

- Ways to break the walking - The current use case for web walking over long distances is trying to reach a specific location than react a specific location for a task. Generally when you are traversing over long distances you would have a goal to accomplish rather than just reaching a certain location which it does now. Whether you are trying to talk to an NPC or start wood cutting. This would allow a user to break early and finalize the path themselves(Whether it is clicking on the tree to give it a smooth transition).
- Run Energy - There is no way to set a minimum run energy/energy to toggle it on.

Edit: More context around run energy min/max:

Its would randomize energy, per time/toggle. It could be unlikely to happen multiple times in a single walk so you could have a single value for run energy and randomize it in the script. Although the value would have to be consistent since you can't control it via the scripters side since webwalking takes control.
An example is if you put 10 energy, then you trigger it like 4 times because you have high weight/low agility. Not sure if every time dead on 10 would be weird.

I believe an example which would be a good API which would follow the current builder pattern used in streams. 
```

new WebWalkingBuilder(Tile t)
.runEnergy(int min, int max)
.condition(Condition condition)
.build()
```

**Comment by constt** [comment]
This has been added in the latest release, check Movement#builder
