### ISSUE TITLE
NPC not being recognized

### ISSUE THREAD

**Issue by chidifrank** [powbot/api#69]
Name returns null

<img width="556" alt="Screenshot 2021-04-02 at 15 05 46" src="https://user-images.githubusercontent.com/35044712/113479919-ee0e1080-9491-11eb-8a92-16799a1b8454.png">

**Comment by CHGOLD514** [comment]
Bro tell me you need accounts

**Comment by constt** [comment]
This will be fixed in an upcoming release.
