### ISSUE TITLE
charter npc's names are null

### ISSUE THREAD

**Issue by gutizia** [powbot/api#73]
![image](https://user-images.githubusercontent.com/51299340/114060954-2b114300-9896-11eb-95b3-d77aa7eefe25.png)
trying to interact with the npcs, the api will hover the npc but wont click on it

**Comment by PTYB** [comment]
Doesnt null refer to the name? If so I know some NPC's have this issue, generally around quest ones I have noticed.

**Comment by gutizia** [comment]
yeah you're right, it refers to the name. I did some more testing, seems like the issue is with how the client gets the name of the npc. I was able to query with id and make it interact properly without referencing the name as I did previously.
the npcs queries are valid with all other info except name being normal it seems

**Comment by constt** [comment]
This should be resolved.
