### ISSUE TITLE
java.awt.event.MouseMotionListener Interfering with Paint

### ISSUE THREAD

**Issue by iDznPB** [powbot/api#8]
Paint thread wouldn't run, even if I cleared everything out and just had a println in there.

Debugging would paint correctly, but the anything inside my paint listener wouldn't activate whilst I have 
java.awt.event.MouseMotionListener active.

**Comment by constt** [comment]
Is this resolved @iDznPB ?

Please share code if not

**Comment by iDznPB** [comment]
Yeah this has been resolved 👍
