### ISSUE TITLE
Web tries to walk straight through obstacles

### ISSUE THREAD

**Issue by dylanblokhuis** [powbot/api#88]
When I use web to walk to blood altar in arceeus, it tries to walk towards it in a straight line instead of traversing with the proper route: 

Where it happened: (the tile near the map icon is my player, the other tile is in an area thats not walkable)
<img src="https://i.imgur.com/6RD0o0y.png" alt="" />

Destination tile given to the web walker:
<img src="https://i.imgur.com/zFSjzc8.png" alt="" />

**Comment by constt** [comment]
This should be resolved in the latest RC
