### ISSUE TITLE
Certain game objects are not registered

### ISSUE THREAD

**Issue by chidifrank** [powbot/api#9]
https://i.gyazo.com/2a60a1d7c6d0c40b5a13fab72641a6fe.mp4 
Lumbridge bank chest - PVP

**Comment by RZME** [comment]
another case: https://i.gyazo.com/02ba6c0a088d26f55e6198baa6307a19.png

**Comment by rvbiljouw** [comment]
Should be fixed in the most recent release, feel free to re-open if you have more issues.
