### ISSUE TITLE
ctx.menu.close() is bugged on mobile

### ISSUE THREAD

**Issue by Krulvis** [powbot/api#95]
For some reason client keeps opening new menu's when you call ctx.menu.close()

https://user-images.githubusercontent.com/21366036/121420486-6b13a580-c96d-11eb-93da-51f1abd84b00.mp4

Code to replicate:
`if (ctx.menu.opened()) {
                ctx.menu.close()
            }`

**Comment by Krulvis** [comment]
It could potentially be fixed by simply clicking on the Cancel button rather than moving away from the menu on mobile.

**Comment by constt** [comment]
should be fixed in next
