### ISSUE TITLE
GameActionEvent needs location fields added

### ISSUE THREAD

**Issue by Krulvis** [powbot/api#97]
GameActionEvent currently contains a `var0` field that represents the localX with opCode 1002. It would be really useful if GameActionEvent contains both localX and localY to be able to get the location of the interaction.

**Comment by constt** [comment]
@Krulvis I think it's called `widgetId`, really shouln't have named the fields tbh as they change depending on action

**Comment by Krulvis** [comment]
If it is then the next issue is having it supported on Mobile client

**Comment by constt** [comment]
This is fixed
